package org.openmrs.module.teammodule;

public class TeamConstants {

	public enum TeamAction {
		TEAM_ROLE_ADDED,
		TEAM_ROLE_EDITED,
		TEAM_ROLE_VOIDED,
		TEAM_HIERARCHY_ADDED,
		TEAM_HIERARCHY_EDITED;				
	}
	
	public enum TeamMemberAction {
		TEAM_MEMBER_EDITED,
		TEAM_MEMBER_VOIDED,
		TEAM_MEMBER_LOCATION_REMOVED,
		TEAM_MEMBER_LOCATION_ADDED,
		TEAM_MEMBER_TEAM_CHANGED,
		TEAM_TRANSFERED,
		TEAM_MEMBER_PATIENT_REMOVED,
		TEAM_MEMBER_PATIENT_ADDED;				
	}
	
}
